// File generated by FlutterFire CLI.
// This is a placeholder file. You need to replace it with your actual Firebase configuration.
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCAJu68frJEjqLIWbEgAUFUPDR84WZ-v0',
    appId: '1:105459263570:web:9d0599d506f304f1ae978b',
    messagingSenderId: '105459263570',
    projectId: 'mobile-643dc',
    authDomain: 'mobile-643dc.firebaseapp.com',
    storageBucket: 'mobile-643dc.firebasestorage.app',
    databaseURL: 'https://mobile-643dc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdpWgP2vBKh9mi9kalQI6OPuz3dRcgtXU',
    appId: '1:105459263570:android:f0320adf923674f8ae978b',
    messagingSenderId: '105459263570',
    projectId: 'mobile-643dc',
    authDomain: 'mobile-643dc.firebaseapp.com',
    databaseURL: 'https://mobile-643dc-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-643dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Rra4cbwO9D-hWFh1kw5h0n89va8KAoA',
    appId: '1:105459263570:ios:bb7806ded40e9dc1ae978b',
    messagingSenderId: '105459263570',
    projectId: 'mobile-643dc',
    authDomain: 'mobile-643dc.firebaseapp.com',
    databaseURL: 'https://mobile-643dc-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-643dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Rra4cbwO9D-hWFh1kw5h0n89va8KAoA',
    appId: '1:105459263570:ios:bb7806ded40e9dc1ae978b',
    messagingSenderId: '105459263570',
    projectId: 'mobile-643dc',
    authDomain: 'mobile-643dc.firebaseapp.com',
    databaseURL: 'https://mobile-643dc-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-643dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCCAJu68frJEjqLIWbEgAUFUPDR84WZ-v0',
    appId: '1:105459263570:web:9d0599d506f304f1ae978b',
    messagingSenderId: '105459263570',
    projectId: 'mobile-643dc',
    authDomain: 'mobile-643dc.firebaseapp.com',
    databaseURL: 'https://mobile-643dc-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-643dc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCAJu68frJEjqLIWbEgAUFUPDR84WZ-v0',
    appId: '1:105459263570:web:6e17c843ae0abaa1ae978b',
    messagingSenderId: '105459263570',
    projectId: 'mobile-643dc',
    authDomain: 'mobile-643dc.firebaseapp.com',
    databaseURL: 'https://mobile-643dc-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-643dc.firebasestorage.app',
  );

}